# Generated by Django 5.1.7 on 2025-04-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='search_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='source',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
