# Generated by Django 5.1.7 on 2025-04-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_faculty_department_alter_faculty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AlterField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.academicprogram'),
        ),
    ]
